name: Convert JPEG to PNG

on:
  push:
    paths:
      - 'media/**' # Trigger only when changes occur in the media folder
  workflow_dispatch: # Allows manual triggering

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Find and Convert JPEGs to PNGs
      run: |
        # Find all .jpeg and .jpg files in /media/
        find media/ -type f \( -iname "*.jpeg" -o -iname "*.jpg" \) | while read file; do
          # Define the new file name with .png extension
          png_file="${file%.*}.png"
          # Convert the image to PNG
          convert "$file" "$png_file"
          echo "Converted $file to $png_file"
        done


    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: "Convert JPEG images to PNG format"
          branch: ${{ github.ref }} # Ensures commits are made to the current branch
          file_pattern: 'media/*.png' # Specifies which files to commit
