name: Convert JPEG to PNG

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Convert JPEGs to PNGs and Delete Originals
      run: |
        # Navigate to the media directory
        cd media
        
        # Find all .jpeg and .jpg files recursively
        find . -type f \( -iname "*.jpeg" -o -iname "*.jpg" \) | while read -r file; do
          # Define the new PNG file name
          png_file="${file%.*}.png"
          
          # Check if PNG already exists and is up-to-date
          if [ ! -f "$png_file" ] || [ "$file" -nt "$png_file" ]; then
            # Convert JPEG/JPG to PNG
            convert "$file" "$png_file"
            echo "Converted $file to $png_file"
            
            # Delete the original JPEG/JPG file
            rm "$file"
            echo "Deleted original file $file"
            ls
          else
            echo "Skipped $file; PNG is up-to-date."
          fi
        done



    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: "Convert JPEG images to PNG format"
          branch: main # Ensures commits are made to the current branch
